apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/cloudside-academy/locations/asia-south1-a/clusters/arjun-codebuild-cluster

